name: Main CI

on:
  push:
    branches:
      - main
      # TODO: remove this once next branch is merged into main
      - next

jobs:
  main-ci:
    runs-on: ubuntu-latest

    environment: CI
    env:
      # Database
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Clerk
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

      NEXT_PUBLIC_CLERK_SIGN_IN_URL: '/sign-in'
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: '/sign-up'
      NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL: '/app'
      NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL: '/app'

      # Upstash
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

      # Resend
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Run DB Migrations
        run: bun db:migrate

      - name: Check Format
        run: bun format:check

      - name: Lint
        run: bun lint

      - name: Typecheck
        run: bun typecheck

      - name: Build
        run: bun run build
